#!/bin/bash
set -e

GREEN='\033[0;32m'
BLUE='\033[0;34m'
RED='\033[0;31m'
NC='\033[0m'

echo -e "${BLUE}Setting up frontend env from deployed CDK stacks...${NC}"

REGION="${AWS_REGION:-us-east-1}"

extract_output() {
  local stack="$1"
  local key="$2"
  aws cloudformation describe-stacks \
    --stack-name "$stack" \
    --region "$REGION" \
    --query "Stacks[0].Outputs[?OutputKey=='${key}'].OutputValue" \
    --output text
}

USER_POOL_ID=$(extract_output "ProjectPlanner-Database" "UserPoolId")
USER_POOL_CLIENT_ID=$(extract_output "ProjectPlanner-Database" "UserPoolClientId")
IDENTITY_POOL_ID=$(extract_output "ProjectPlanner-Database" "IdentityPoolId")
PLANS_TABLE=$(extract_output "ProjectPlanner-Database" "PlansTableName")
DISTRIBUTION_DOMAIN=$(extract_output "ProjectPlanner-Database" "DistributionDomain")
WORKFLOW_ARN=$(extract_output "ProjectPlanner-Workflow" "WorkflowArn")
HANDOFF_TABLE=$(extract_output "ProjectPlanner-Database" "HandoffTableName")

ENV_FILE="apps/web/.env"
cat > "$ENV_FILE" << EOF
# Auto-generated by scripts/setup-env.sh — DO NOT COMMIT
VITE_AWS_REGION=${REGION}
VITE_USER_POOL_ID=${USER_POOL_ID}
VITE_USER_POOL_CLIENT_ID=${USER_POOL_CLIENT_ID}
VITE_IDENTITY_POOL_ID=${IDENTITY_POOL_ID}
VITE_PLANS_TABLE=${PLANS_TABLE}
VITE_HANDOFF_TABLE=${HANDOFF_TABLE}
VITE_WORKFLOW_ARN=${WORKFLOW_ARN}
VITE_DISTRIBUTION_DOMAIN=${DISTRIBUTION_DOMAIN}
EOF

echo -e "${GREEN}apps/web/.env written${NC}"
echo ""
echo -e "${BLUE}Values:${NC}"
echo "  Region:           ${REGION}"
echo "  User Pool:        ${USER_POOL_ID}"
echo "  Identity Pool:    ${IDENTITY_POOL_ID}"
echo "  Plans Table:      ${PLANS_TABLE}"
echo "  Handoff Table:    ${HANDOFF_TABLE}"
echo "  Workflow ARN:     ${WORKFLOW_ARN}"
echo "  CloudFront:       ${DISTRIBUTION_DOMAIN}"
echo ""
echo -e "${BLUE}Next steps:${NC}"
echo "  Local dev:  cd apps/web && npm run dev"
